#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube environmentMap;

layout(set = 0, binding = 1, rgba16f) uniform writeonly imageCube irradianceMap;

const float PI = 3.14159265359;

vec3 GetCubemapVector(ivec3 globalId, vec2 imageSize)
{
    vec2 uv = vec2(globalId.xy) / imageSize;
    uv = uv * 2.0 - 1.0; 
    uint face = globalId.z;
    vec3 dir = vec3(0.0);
    switch (face) {
        case 0: dir = vec3( 1.0, -uv.y, -uv.x); break; 
        case 1: dir = vec3(-1.0, -uv.y,  uv.x); break; 
        case 2: dir = vec3( uv.x,  1.0,  uv.y); break; 
        case 3: dir = vec3( uv.x, -1.0, -uv.y); break; 
        case 4: dir = vec3( uv.x, -uv.y,  1.0); break; 
        case 5: dir = vec3(-uv.x, -uv.y, -1.0); break; 
    }
    return normalize(dir);
}

void main()
{
    ivec3 globalId = ivec3(gl_GlobalInvocationID);
    ivec2 imageSize = imageSize(irradianceMap);

    if (globalId.x >= imageSize.x || globalId.y >= imageSize.y) return;

  
    vec3 normal = GetCubemapVector(globalId, vec2(imageSize));

    vec3 up    = vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, normal));
    up         = normalize(cross(normal, right));

    vec3 irradiance = vec3(0.0);   
    float sampleDelta = 0.025; 
    float nrSamples = 0.0; 

    // We iterate over the hemisphere defined by the surface normal.
    // Phi ranges from 0 to 2PI (around the horizon).
    // Theta ranges from 0 to PI/2 (from the pole to the horizon).
    for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
    {
        for(float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta)
        {
           // Convert spherical coordinates to cartesian (x,y,z)
            vec3 tangentSample = vec3(sin(theta) * cos(phi),  sin(theta) * sin(phi), cos(theta));
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal; 

            // Scale by cos(theta) (weaker light at grazing angles) 
            // and sin(theta) (compensating for smaller sample areas at the pole)
            irradiance += textureLod(environmentMap, sampleVec, 4.0).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    
    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    
    imageStore(irradianceMap, globalId, vec4(irradiance, 1.0));
}