#version 460
#extension GL_EXT_ray_tracing : require

#include "Common/LightingHelpers.glsl"
#include "Common/CommonHelpers.glsl"

layout(location = 0) rayPayloadEXT float hitValue;

layout(set = 0, binding = 0) uniform CameraUBO {
    mat4 view;
    mat4 proj;
    mat4 invView;
    mat4 invProj;
    mat4 invViewProj;
    mat4 invProjUnjittered;
    mat4 viewProj;
    mat4 prevViewProj;
} camera;

layout(set = 1, binding = 0) uniform accelerationStructureEXT topLevelAS;

layout(set = 2, binding = 0) uniform sampler2D samplerDepth;
layout(set = 2, binding = 1) uniform sampler2D samplerNormal;
layout(set = 2, binding = 2, rgba16f) uniform writeonly image2D outAOMask; 

layout(push_constant) uniform PushConsts {
    uint frameCount;
    uint spp;
} pc;

uint pcg_hash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float rnd(inout uint seed) {
    seed = pcg_hash(seed);
    return float(seed) / 4294967296.0;
}

void main() 
{
    ivec2 pixelCoord = ivec2(gl_LaunchIDEXT.xy);
    vec2 resolution = vec2(gl_LaunchSizeEXT.xy);
    vec2 uv = (vec2(pixelCoord) + 0.5) / resolution;

    float depth = texture(samplerDepth, uv).r;


    if (depth >= 0.9999) {
        imageStore(outAOMask, pixelCoord, vec4(1.0));
        return;
    }

    vec3 worldPos = reconstructWorldPos(depth, uv, camera.invViewProj);
    vec3 normal = normalize(texture(samplerNormal, uv).xyz);


    float accumulatedAO = 0.0;

    for(uint i = 0; i < pc.spp; ++i)
    {
       
        uint seed = pixelCoord.x + pixelCoord.y * uint(resolution.x) + pc.frameCount * 719393 + i * 1337;

        vec2 randVal = vec2(rnd(seed), rnd(seed));
        float z = sqrt(1.0 - randVal.y);
        float phi = 2.0 * PI * randVal.x;
        float x = cos(phi) * sqrt(randVal.y);
        float y = sin(phi) * sqrt(randVal.y);
        vec3 localDir = vec3(x, y, z);

      
        vec3 up = abs(normal.z) < 0.999 ? vec3(0,0,1) : vec3(1,0,0);
        vec3 tangent = normalize(cross(up, normal));
        vec3 bitangent = cross(normal, tangent);
        vec3 worldDir = tangent * localDir.x + bitangent * localDir.y + normal * localDir.z;

        vec3 origin = worldPos + (normal * 0.05);

        uint rayFlags = gl_RayFlagsTerminateOnFirstHitEXT | 
                        gl_RayFlagsOpaqueEXT | 
                        gl_RayFlagsSkipClosestHitShaderEXT;

        float tMin = 0.001;
        float tMax = 1.5; 

        hitValue = 0.0; 

        traceRayEXT(
            topLevelAS,    
            rayFlags,      
            0xFF,          
            0,             
            0,             
            0,             
            origin,        
            tMin,          
            worldDir,      
            tMax,          
            0              
        );


        accumulatedAO += hitValue;
    }

 
    float finalAO = accumulatedAO / float(pc.spp);
    imageStore(outAOMask, pixelCoord, vec4(finalAO, finalAO, finalAO, 1.0));
}