#version 460
#extension GL_EXT_ray_tracing : require

#include "Common/LightingHelpers.glsl"
#include "Common/CommonHelpers.glsl"

layout(location = 0) rayPayloadEXT vec4 hitValue;

layout(set = 0, binding = 0) uniform CameraUBO {
    mat4 view;
    mat4 proj;
    mat4 invView;
    mat4 invProj;
    mat4 invViewProj;
    mat4 invProjUnjittered;
    mat4 viewProj;
    mat4 prevViewProj;
} camera;

layout(set = 1, binding = 0) uniform accelerationStructureEXT topLevelAS;

layout(set = 2, binding = 0) uniform sampler2D samplerDepth;
layout(set = 2, binding = 1) uniform sampler2D samplerNormal;
layout(set = 2, binding = 2) uniform sampler2D samplerMaterial;
layout(set = 2, binding = 3, rgba16f) uniform writeonly image2D outRTR;

layout(push_constant) uniform PushConsts {
    uint frameCount;
    uint spp;
} pc;


uint pcg_hash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float rnd(inout uint seed) {
    seed = pcg_hash(seed);
    return float(seed) / 4294967296.0;
}

void main() 
{
    ivec2 pixelCoord = ivec2(gl_LaunchIDEXT.xy);
    vec2 resolution = vec2(gl_LaunchSizeEXT.xy);
    vec2 uv = (vec2(pixelCoord) + 0.5) / resolution;

    float depth = texture(samplerDepth, uv).r;

    if (depth >= 0.9999) {
        imageStore(outRTR, pixelCoord, vec4(0.0));
        return;
    }

    vec4 material = texture(samplerMaterial, uv);
    float roughness = material.g;

    if (roughness > 0.4) {
        imageStore(outRTR, pixelCoord, vec4(0.0));
        return;
    }

    vec3 worldPos = reconstructWorldPos(depth, uv, camera.invViewProj);
    vec3 normal = normalize(texture(samplerNormal, uv).xyz);
    vec3 viewPos = (camera.invView * vec4(0, 0, 0, 1)).xyz;
    vec3 viewDir = normalize(worldPos - viewPos);

    vec3 reflectDir = normalize(reflect(viewDir, normal));
    vec3 origin = worldPos + (normal * 0.001);

    uint rayFlags = gl_RayFlagsOpaqueEXT;
    float tMin = 0.01;
    float tMax = 1000.0; 

    vec3 accumulatedColor = vec3(0.0);

    for (uint i = 0; i < pc.spp; ++i) {
      
        uint seed = pixelCoord.x + pixelCoord.y * uint(resolution.x) + pc.frameCount * 719393 + i * 1337;

        vec3 jitter = vec3(
            rnd(seed) * 2.0 - 1.0, 
            rnd(seed) * 2.0 - 1.0, 
            rnd(seed) * 2.0 - 1.0
        );

        jitter = normalize(jitter) * rnd(seed) * roughness;
        vec3 sampleDir = normalize(reflectDir + jitter);

        if (dot(sampleDir, normal) <= 0.01) {
            sampleDir = reflectDir;
        }

        hitValue = vec4(0.0, 0.0, 0.0, 1.0);

        traceRayEXT(
            topLevelAS,    
            rayFlags,      
            0xFF,          
            0,             // sbtRecordOffset
            0,             // sbtRecordStride
            0,             // missIndex
            origin,        
            tMin,          
            sampleDir,     
            tMax,          
            0              // payloadLocation
        );

        accumulatedColor += hitValue.rgb;
    }

 
    vec3 finalReflection = accumulatedColor / float(pc.spp);

    float roughnessFade = 1.0 - smoothstep(0.2, 0.4, roughness);
    finalReflection *= roughnessFade;

    imageStore(outRTR, pixelCoord, vec4(finalReflection, 1.0));
}