#version 450
vec3 ACESFilm(in vec3 color)
{
    float a = 2.51f;
    float b = 0.03f;
    float c = 2.43f;
    float d = 0.59f;
    float e = 0.14f;
    return clamp((color * (a * color + b)) / (color * (c * color + d) + e), 0.0, 1.0);
}

layout(push_constant) uniform Params {
    float aperture;
    float shutterSpeed;
    float iso;
} camera;

layout(set = 0, binding = 0) uniform sampler2D hdrTexture; 
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D ldrOutput;

layout(set = 0, binding = 2, std430) readonly buffer ExposureBuffer {
    float exposure;
} eye;


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() 
{
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imageSize = textureSize(hdrTexture, 0); 

    if (pixelCoord.x >= imageSize.x || pixelCoord.y >= imageSize.y) return;
    
    vec3 color = texelFetch(hdrTexture, pixelCoord, 0).rgb; 


  float ev100 = log2((camera.aperture * camera.aperture) / camera.shutterSpeed) - log2(camera.iso / 100.0);

   
  float finalEV100 = ev100 + eye.exposure;

  float physicalMultiplier = 1.0 / (1.2 * exp2(finalEV100));

    color *= physicalMultiplier;
    vec3 ldrColor = ACESFilm(color);
    imageStore(ldrOutput, pixelCoord, vec4(ldrColor, 1.0)); 
}