#ifndef GEOMETRY_PASS_H
#define GEOMETRY_PASS_H
#include "../RenderGraph/Pass.h"
#include "../Core/ResourceManager.h"
#include "../RenderGraph/RenderGraphTypes.h"
#include "../Core/Pipeline.h"
#include "../RenderGraph/RenderGraph.h"
#include <vulkan/vulkan.h>

namespace Core {
    class Scene;
}

namespace Render::Pass
{
	/// @brief Renders opaque scene geometry into a Multi-Render Target (MRT) G-Buffer.
    /// Relies on an existing depth buffer to utilize Early-Z testing for maximum performance.
    /// 
    /// @note Inputs: "SceneDepth" (DepthRead - Generated by DepthPrePass)
    /// @note Outputs: "GBuffer_Albedo", "GBuffer_Normal", "GBuffer_Material"
    class GeometryPass : public Graph::Pass
    {
    public:
        GeometryPass(const std::string& name,
            VkExtent2D extent,
           Core::ResourceManager* resManager,
            const Core::Scene* scene)
            : Pass(name), m_extent(extent), m_resourceManager(resManager), m_scene(scene) {

            Core::GraphicsPipelineConfig geomConfig{};
            geomConfig.vertexShader = "shaders/geometry.vert.spv";
            geomConfig.fragmentShader = "shaders/geometry.frag.spv";
            geomConfig.descriptorLayouts = { m_resourceManager->GetGlobalDescriptorSet().layout };
            geomConfig.pushConstants = {
                { VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(RenderTypes::PassPushConstants) }
            };
            geomConfig.colorFormats = {
                VK_FORMAT_R8G8B8A8_SRGB,
                VK_FORMAT_R16G16B16A16_SFLOAT,
                VK_FORMAT_R8G8B8A8_UNORM,
            };
            geomConfig.depthFormat = VK_FORMAT_D32_SFLOAT;
            geomConfig.enableDepthTest = true;
            // Because we already ran a Depth Pre-Pass, the Z-buffer is perfectly primed.
			// By setting the depth compare op to EQUAL, the GPU will strictly only execute 
			// this expensive G-Buffer fragment shader if the pixel is 100% visible, completely eliminating overdraw.
            geomConfig.enableDepthWrite = false; // Relying on PrePass depth!
            geomConfig.depthCompareOp = VK_COMPARE_OP_EQUAL;
            geomConfig.cullMode = VK_CULL_MODE_NONE;

            Core::PipelineBuilder Pipelinebuilder(m_resourceManager->GetContext());

            m_pipeline = Core::PipelineFactory::CreateGraphics(&Pipelinebuilder, geomConfig);

        }

        ~GeometryPass() override;
        

        void Setup(Graph::RenderGraphBuilder& builder) override;
        void Execute(const RenderTypes::RenderContext& context, Render::Graph::RenderGraph& graph) override;
        bool HasSideEffect() override { return true; }

       Render::Graph::RGHandle GetAlbedoHandle()   const { return m_Albedo; }
       Render::Graph::RGHandle GetNormalHandle()   const { return m_Normal; }
       Render::Graph::RGHandle GetMaterialHandle() const { return m_Material; }
       Render::Graph::RGHandle GetDepthHandle()    const { return m_Depth; }

    private:
        Render::Graph::RGHandle m_Albedo;
        Render::Graph::RGHandle m_Normal;
        Render::Graph::RGHandle m_Material;
        Render::Graph::RGHandle m_Depth;   

        VkExtent2D m_extent;
        std::unique_ptr<Core::PipelineBuilder::Pipeline> m_pipeline;
        Core::ResourceManager* m_resourceManager;
        const Core::Scene* m_scene;
    };
}
#endif